2025-09-03 18:20:21,058 INFO: Microblog startup [in C:\Users\monic\Vetor\microblog\app\__init__.py:40]
2025-09-03 18:20:56,780 ERROR: Exception on /edit_profile [GET] [in C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\Vetor\microblog\app\routes.py", line 92, in edit_profile
    form = EditProfileForm(current_user.username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\wtforms\form.py", line 209, in __call__
    return type.__call__(cls, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\Vetor\microblog\app\forms.py", line 39, in __init__
    super().__init__(*args, **kwards)
                              ^^^^^^
NameError: name 'kwards' is not defined
2025-09-03 18:21:06,419 ERROR: Exception on /edit_profile [GET] [in C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\Vetor\microblog\app\routes.py", line 92, in edit_profile
    form = EditProfileForm(current_user.username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\wtforms\form.py", line 209, in __call__
    return type.__call__(cls, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\Vetor\microblog\app\forms.py", line 39, in __init__
    super().__init__(*args, **kwards)
                              ^^^^^^
NameError: name 'kwards' is not defined
2025-09-03 18:21:43,817 ERROR: Exception on /edit_profile [GET] [in C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\Vetor\microblog\app\routes.py", line 92, in edit_profile
    form = EditProfileForm(current_user.username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\wtforms\form.py", line 209, in __call__
    return type.__call__(cls, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\Vetor\microblog\app\forms.py", line 39, in __init__
    super().__init__(*args, **kwargs)
                              ^^^^^^
NameError: name 'kwards' is not defined
2025-09-03 18:21:53,100 ERROR: Exception on /edit_profile [GET] [in C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\Vetor\microblog\app\routes.py", line 92, in edit_profile
    form = EditProfileForm(current_user.username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\AppData\Local\Programs\Python\Python311\Lib\site-packages\wtforms\form.py", line 209, in __call__
    return type.__call__(cls, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monic\Vetor\microblog\app\forms.py", line 39, in __init__
    super().__init__(*args, **kwargs)
                              ^^^^^^
NameError: name 'kwards' is not defined
2025-09-03 18:22:45,382 INFO: Microblog startup [in C:\Users\monic\Vetor\microblog\app\__init__.py:40]
2025-09-04 10:35:43,449 INFO: Microblog startup [in C:\Users\monic\Vetor\microblog\app\__init__.py:40]
2025-09-04 10:36:11,076 INFO: Microblog startup [in C:\Users\monic\Vetor\microblog\app\__init__.py:40]
2025-09-04 10:36:57,667 INFO: Microblog startup [in C:\Users\monic\Vetor\microblog\app\__init__.py:40]
2025-09-04 10:38:17,634 INFO: Microblog startup [in C:\Users\monic\Vetor\microblog\app\__init__.py:40]
2025-09-04 10:39:11,063 INFO: Microblog startup [in C:\Users\monic\Vetor\microblog\app\__init__.py:40]
